export const hiragana = [
  // Basic vowels
  { kana: "あ", romaji: "a", group: "vowels" },
  { kana: "い", romaji: "i", group: "vowels" },
  { kana: "う", romaji: "u", group: "vowels" },
  { kana: "え", romaji: "e", group: "vowels" },
  { kana: "お", romaji: "o", group: "vowels" },
  // K
  { kana: "か", romaji: "ka", group: "k" },
  { kana: "き", romaji: "ki", group: "k" },
  { kana: "く", romaji: "ku", group: "k" },
  { kana: "け", romaji: "ke", group: "k" },
  { kana: "こ", romaji: "ko", group: "k" },
  // S
  { kana: "さ", romaji: "sa", group: "s" },
  { kana: "し", romaji: "shi", group: "s" },
  { kana: "す", romaji: "su", group: "s" },
  { kana: "せ", romaji: "se", group: "s" },
  { kana: "そ", romaji: "so", group: "s" },
  // T
  { kana: "た", romaji: "ta", group: "t" },
  { kana: "ち", romaji: "chi", group: "t" },
  { kana: "つ", romaji: "tsu", group: "t" },
  { kana: "て", romaji: "te", group: "t" },
  { kana: "と", romaji: "to", group: "t" },
  // N
  { kana: "な", romaji: "na", group: "n" },
  { kana: "に", romaji: "ni", group: "n" },
  { kana: "ぬ", romaji: "nu", group: "n" },
  { kana: "ね", romaji: "ne", group: "n" },
  { kana: "の", romaji: "no", group: "n" },
  // H
  { kana: "は", romaji: "ha", group: "h" },
  { kana: "ひ", romaji: "hi", group: "h" },
  { kana: "ふ", romaji: "fu", group: "h" },
  { kana: "へ", romaji: "he", group: "h" },
  { kana: "ほ", romaji: "ho", group: "h" },
  // M
  { kana: "ま", romaji: "ma", group: "m" },
  { kana: "み", romaji: "mi", group: "m" },
  { kana: "む", romaji: "mu", group: "m" },
  { kana: "め", romaji: "me", group: "m" },
  { kana: "も", romaji: "mo", group: "m" },
  // Y
  { kana: "や", romaji: "ya", group: "y" },
  { kana: "ゆ", romaji: "yu", group: "y" },
  { kana: "よ", romaji: "yo", group: "y" },
  // R
  { kana: "ら", romaji: "ra", group: "r" },
  { kana: "り", romaji: "ri", group: "r" },
  { kana: "る", romaji: "ru", group: "r" },
  { kana: "れ", romaji: "re", group: "r" },
  { kana: "ろ", romaji: "ro", group: "r" },
  // W
  { kana: "わ", romaji: "wa", group: "w" },
  { kana: "を", romaji: "wo", group: "w" },
  // W
  { kana: "ん", romaji: "n", group: "w" },
  // G
  { kana: "が", romaji: "ga", group: "g" },
  { kana: "ぎ", romaji: "gi", group: "g" },
  { kana: "ぐ", romaji: "gu", group: "g" },
  { kana: "げ", romaji: "ge", group: "g" },
  { kana: "ご", romaji: "go", group: "g" },
  // Z
  { kana: "ざ", romaji: "za", group: "z" },
  { kana: "じ", romaji: "ji", group: "z" },
  { kana: "ず", romaji: "zu", group: "z" },
  { kana: "ぜ", romaji: "ze", group: "z" },
  { kana: "ぞ", romaji: "zo", group: "z" },
  // D
  { kana: "だ", romaji: "da", group: "d" },
  { kana: "ぢ", romaji: "ji", group: "d" },
  { kana: "づ", romaji: "zu", group: "d" },
  { kana: "で", romaji: "de", group: "d" },
  { kana: "ど", romaji: "do", group: "d" },
  // B
  { kana: "ば", romaji: "ba", group: "b" },
  { kana: "び", romaji: "bi", group: "b" },
  { kana: "ぶ", romaji: "bu", group: "b" },
  { kana: "べ", romaji: "be", group: "b" },
  { kana: "ぼ", romaji: "bo", group: "b" },
  // P
  { kana: "ぱ", romaji: "pa", group: "p" },
  { kana: "ぴ", romaji: "pi", group: "p" },
  { kana: "ぷ", romaji: "pu", group: "p" },
  { kana: "ぺ", romaji: "pe", group: "p" },
  { kana: "ぽ", romaji: "po", group: "p" },

  // COMBINATIONS (Digraphs) - Hiragana
  // K + y combinations
  { kana: "きゃ", romaji: "kya", group: "combinationsK" },
  { kana: "きゅ", romaji: "kyu", group: "combinationsK" },
  { kana: "きょ", romaji: "kyo", group: "combinationsK" },
  // S + y combinations
  { kana: "しゃ", romaji: "sha", group: "combinationsS" },
  { kana: "しゅ", romaji: "shu", group: "combinationsS" },
  { kana: "しょ", romaji: "sho", group: "combinationsS" },
  // C/T + y combinations
  { kana: "ちゃ", romaji: "cha", group: "combinationsC" },
  { kana: "ちゅ", romaji: "chu", group: "combinationsC" },
  { kana: "ちょ", romaji: "cho", group: "combinationsC" },
  // N + y combinations
  { kana: "にゃ", romaji: "nya", group: "combinationsN" },
  { kana: "にゅ", romaji: "nyu", group: "combinationsN" },
  { kana: "にょ", romaji: "nyo", group: "combinationsN" },
  // H + y combinations
  { kana: "ひゃ", romaji: "hya", group: "combinationsH" },
  { kana: "ひゅ", romaji: "hyu", group: "combinationsH" },
  { kana: "ひょ", romaji: "hyo", group: "combinationsH" },
  // M + y combinations
  { kana: "みゃ", romaji: "mya", group: "combinationsM" },
  { kana: "みゅ", romaji: "myu", group: "combinationsM" },
  { kana: "みょ", romaji: "myo", group: "combinationsM" },
  // R + y combinations
  { kana: "りゃ", romaji: "rya", group: "combinationsR" },
  { kana: "りゅ", romaji: "ryu", group: "combinationsR" },
  { kana: "りょ", romaji: "ryo", group: "combinationsR" },
  // G + y combinations (voiced)
  { kana: "ぎゃ", romaji: "gya", group: "combinationsG" },
  { kana: "ぎゅ", romaji: "gyu", group: "combinationsG" },
  { kana: "ぎょ", romaji: "gyo", group: "combinationsG" },
  // J/Z + y combinations
  { kana: "じゃ", romaji: "ja", group: "combinationsJ" },
  { kana: "じゅ", romaji: "ju", group: "combinationsJ" },
  { kana: "じょ", romaji: "jo", group: "combinationsJ" },
  // B + y combinations
  { kana: "びゃ", romaji: "bya", group: "combinationsB" },
  { kana: "びゅ", romaji: "byu", group: "combinationsB" },
  { kana: "びょ", romaji: "byo", group: "combinationsB" },
  // P + y combinations
  { kana: "ぴゃ", romaji: "pya", group: "combinationsP" },
  { kana: "ぴゅ", romaji: "pyu", group: "combinationsP" },
  { kana: "ぴょ", romaji: "pyo", group: "combinationsP" },
];

export const katakana = [
  { kana: "ア", romaji: "a", group: "vowels" },
  { kana: "イ", romaji: "i", group: "vowels" },
  { kana: "ウ", romaji: "u", group: "vowels" },
  { kana: "エ", romaji: "e", group: "vowels" },
  { kana: "オ", romaji: "o", group: "vowels" },
  { kana: "カ", romaji: "ka", group: "k" },
  { kana: "キ", romaji: "ki", group: "k" },
  { kana: "ク", romaji: "ku", group: "k" },
  { kana: "ケ", romaji: "ke", group: "k" },
  { kana: "コ", romaji: "ko", group: "k" },
  { kana: "サ", romaji: "sa", group: "s" },
  { kana: "シ", romaji: "shi", group: "s" },
  { kana: "ス", romaji: "su", group: "s" },
  { kana: "セ", romaji: "se", group: "s" },
  { kana: "ソ", romaji: "so", group: "s" },
  { kana: "タ", romaji: "ta", group: "t" },
  { kana: "チ", romaji: "chi", group: "t" },
  { kana: "ツ", romaji: "tsu", group: "t" },
  { kana: "テ", romaji: "te", group: "t" },
  { kana: "ト", romaji: "to", group: "t" },
  { kana: "ナ", romaji: "na", group: "n" },
  { kana: "ニ", romaji: "ni", group: "n" },
  { kana: "ヌ", romaji: "nu", group: "n" },
  { kana: "ネ", romaji: "ne", group: "n" },
  { kana: "ノ", romaji: "no", group: "n" },
  { kana: "ハ", romaji: "ha", group: "h" },
  { kana: "ヒ", romaji: "hi", group: "h" },
  { kana: "フ", romaji: "fu", group: "h" },
  { kana: "ヘ", romaji: "he", group: "h" },
  { kana: "ホ", romaji: "ho", group: "h" },
  { kana: "マ", romaji: "ma", group: "m" },
  { kana: "ミ", romaji: "mi", group: "m" },
  { kana: "ム", romaji: "mu", group: "m" },
  { kana: "メ", romaji: "me", group: "m" },
  { kana: "モ", romaji: "mo", group: "m" },
  { kana: "ヤ", romaji: "ya", group: "y" },
  { kana: "ユ", romaji: "yu", group: "y" },
  { kana: "ヨ", romaji: "yo", group: "y" },
  { kana: "ラ", romaji: "ra", group: "r" },
  { kana: "リ", romaji: "ri", group: "r" },
  { kana: "ル", romaji: "ru", group: "r" },
  { kana: "レ", romaji: "re", group: "r" },
  { kana: "ロ", romaji: "ro", group: "r" },
  { kana: "ワ", romaji: "wa", group: "w" },
  { kana: "ヲ", romaji: "wo", group: "w" },
  { kana: "ン", romaji: "n", group: "w" },
  { kana: "ガ", romaji: "ga", group: "g" },
  { kana: "ギ", romaji: "gi", group: "g" },
  { kana: "グ", romaji: "gu", group: "g" },
  { kana: "ゲ", romaji: "ge", group: "g" },
  { kana: "ゴ", romaji: "go", group: "g" },
  { kana: "ザ", romaji: "za", group: "z" },
  { kana: "ジ", romaji: "ji", group: "z" },
  { kana: "ズ", romaji: "zu", group: "z" },
  { kana: "ゼ", romaji: "ze", group: "z" },
  { kana: "ゾ", romaji: "zo", group: "z" },
  { kana: "ダ", romaji: "da", group: "d" },
  { kana: "ヂ", romaji: "ji", group: "d" },
  { kana: "ヅ", romaji: "zu", group: "d" },
  { kana: "デ", romaji: "de", group: "d" },
  { kana: "ド", romaji: "do", group: "d" },
  { kana: "バ", romaji: "ba", group: "b" },
  { kana: "ビ", romaji: "bi", group: "b" },
  { kana: "ブ", romaji: "bu", group: "b" },
  { kana: "ベ", romaji: "be", group: "b" },
  { kana: "ボ", romaji: "bo", group: "b" },
  { kana: "パ", romaji: "pa", group: "p" },
  { kana: "ピ", romaji: "pi", group: "p" },
  { kana: "プ", romaji: "pu", group: "p" },
  { kana: "ペ", romaji: "pe", group: "p" },
  { kana: "ポ", romaji: "po", group: "p" },

  // COMBINATIONS (Digraphs) - Katakana
  { kana: "キャ", romaji: "kya", group: "combinationsK" },
  { kana: "キュ", romaji: "kyu", group: "combinationsK" },
  { kana: "キョ", romaji: "kyo", group: "combinationsK" },
  { kana: "シャ", romaji: "sha", group: "combinationsS" },
  { kana: "シュ", romaji: "shu", group: "combinationsS" },
  { kana: "ショ", romaji: "sho", group: "combinationsS" },
  { kana: "チャ", romaji: "cha", group: "combinationsT" },
  { kana: "チュ", romaji: "chu", group: "combinationsT" },
  { kana: "チョ", romaji: "cho", group: "combinationsT" },
  { kana: "ニャ", romaji: "nya", group: "combinationsN" },
  { kana: "ニュ", romaji: "nyu", group: "combinationsN" },
  { kana: "ニョ", romaji: "nyo", group: "combinationsN" },
  { kana: "ヒャ", romaji: "hya", group: "combinationsH" },
  { kana: "ヒュ", romaji: "hyu", group: "combinationsH" },
  { kana: "ヒョ", romaji: "hyo", group: "combinationsH" },
  { kana: "ミャ", romaji: "mya", group: "combinationsM" },
  { kana: "ミュ", romaji: "myu", group: "combinationsM" },
  { kana: "ミョ", romaji: "myo", group: "combinationsM" },
  { kana: "リャ", romaji: "rya", group: "combinationsR" },
  { kana: "リュ", romaji: "ryu", group: "combinationsR" },
  { kana: "リョ", romaji: "ryo", group: "combinationsR" },
  { kana: "ギャ", romaji: "gya", group: "combinationsG" },
  { kana: "ギュ", romaji: "gyu", group: "combinationsG" },
  { kana: "ギョ", romaji: "gyo", group: "combinationsG" },
  { kana: "ジャ", romaji: "ja", group: "combinationsJ" },
  { kana: "ジュ", romaji: "ju", group: "combinationsJ" },
  { kana: "ジョ", romaji: "jo", group: "combinationsJ" },
  { kana: "ビャ", romaji: "bya", group: "combinationsB" },
  { kana: "ビュ", romaji: "byu", group: "combinationsB" },
  { kana: "ビョ", romaji: "byo", group: "combinationsB" },
  { kana: "ピャ", romaji: "pya", group: "combinationsP" },
  { kana: "ピュ", romaji: "pyu", group: "combinationsP" },
  { kana: "ピョ", romaji: "pyo", group: "combinationsP" },
];

export const groupLabels = {
  vowels: "Vowels (a i u e o)",
  k: "K (ka ki ku ke ko)",
  s: "S (sa shi su se so)",
  t: "T (ta chi tsu te to)",
  n: "N (na ni nu ne no)",
  h: "H (ha hi fu he ho)",
  m: "M (ma mi mu me mo)",
  y: "Y (ya yu yo)",
  r: "R (ra ri ru re ro)",
  w: "W (wa wo n)",
  g: "G (ga gi gu ge go)",
  z: "Z (za ji zu ze zo)",
  d: "D (da ji zu de do)",
  b: "B (ba bi bu be bo)",
  p: "P (pa pi pu pe po)",
  combinationsK: "Yōon (kya, kyu, kyo)",
  combinationsS: "Yōon (sha, shu, sho)",
  combinationsT: "Yōon (cha, chu, cho)",
  combinationsN: "Yōon (nya, nyu, nyo)",
  combinationsH: "Yōon (hya, hyu, hyo)",
  combinationsM: "Yōon (mya, myu, myo)",
  combinationsR: "Yōon (rya, ryu, ryo)",
  combinationsG: "Yōon (gya, gyu, gyo)",
  combinationsJ: "Yōon (ja, ju, jo)",
  combinationsB: "Yōon (bya, byu, byo)",
  combinationsP: "Yōon (pya, pyu, pyo)",
};

export const fonts = [
  { id: "default", label: "Default", family: "'Noto Sans JP', sans-serif" },
  { id: "serif", label: "Serif", family: "'Noto Serif JP', serif" },
  { id: "mincho", label: "Mincho", family: "'BIZ UDMincho', serif" },
  { id: "gothic", label: "Gothic", family: "'M PLUS 1p', sans-serif" },
  {
    id: "rounded",
    label: "Rounded",
    family: "'M PLUS Rounded 1c', sans-serif",
  },
  { id: "handwritten", label: "Handwritten", family: "'Yomogi', cursive" },
];
